
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: "[^/]+$"
#      - id: tfupdate
      - id: terraform_docs
        args:
          - '--args=--lockfile=false'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      
